Skyline/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Skyline.DbContexts;
using Skyline.Models;

namespace Skyline.Controllers
{
	public class DepartmentsController : Controller
	{
		private readonly ApplicationDbContext _context;

		public DepartmentsController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: Departments
		public async Task<IActionResult> Index()
		{
			return View(await _context.Departments.ToListAsync());
		}

		// GET: Departments/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var department = await _context.Departments.Include(dept => dept.Employees).FirstOrDefaultAsync(m => m.Id == id);

			if (department == null)
			{
				return NotFound();
			}

			return View(department);
		}

		// GET: Departments/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Departments/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name,Description")] Department department)
		{
			if (ModelState.IsValid)
			{
				_context.Add(department);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(department);
		}

		// GET: Departments/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var department = await _context.Departments.FindAsync(id);
			if (department == null)
			{
				return NotFound();
			}
			return View(department);
		}

		// POST: Departments/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Department department)
		{
			if (id != department.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(department);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!DepartmentExists(department.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(department);
		}

		// GET: Departments/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var department = await _context.Departments.Include(d => d.Employees).FirstOrDefaultAsync(m => m.Id == id);
			if (department == null)
			{
				return NotFound();
			}

			return View(department);
		}

		// POST: Departments/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var department = await _context.Departments.FindAsync(id);
			if (department != null)
			{
				_context.Departments.Remove(department);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool DepartmentExists(int id)
		{
			return _context.Departments.Any(e => e.Id == id);
		}
	}
}

Skyline/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using Skyline.Models;
using Skyline.DbContexts;

namespace Skyline.Controllers
{
	public class EmployeesController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly IWebHostEnvironment _webHostEnvironment;



		public EmployeesController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
		{
			_context = context;
			_webHostEnvironment = webHostEnvironment;

		}


		//    List<Employee> employees = new List<Employee>()
		//{
		//    new Employee(){
		//            Id = 1001,
		//            FullName = "Abdelrahman Sayed ",
		//            NationalId = "11022033044",
		//            Position = "Pen Tester",
		//            Salary = 9000m
		//        },
		//    new Employee(){
		//            Id = 1002,
		//            FullName = "Wael Mahmoud ",
		//            NationalId = "100220030044",
		//            Position = "Developer",
		//            Salary = 14500m
		//        },
		//    new Employee(){
		//            Id = 1003,
		//            FullName = "Bahaa Ahmed ",
		//            NationalId = "10022055010",
		//            Position = "Team Lead",
		//            Salary = 19500m
		//        },

		//};
		//public IActionResult GetIndexView()
		//{
		//	ViewBag.EmpCountries = new List<string>() { "Egypt", "Sudan", "Kuwait", "Oman" };

		//	return View("Index", _context.Employees.ToList());
		//}

		//public IActionResult Index() { return View(); }


		[HttpGet]
		public IActionResult GetIndexView(string? search)
		{
			ViewBag.EmpCountries = new List<string>() { "Egypt", "Sudan", "Kuwait", "Oman" };

			ViewBag.SearchText = search;

			IQueryable<Employee> QueryableEmps = _context.Employees.AsQueryable();

			if (string.IsNullOrEmpty(search) == false)
			{
				QueryableEmps = QueryableEmps.Where(emp => emp.FullName.Contains(search) || emp.Position.Contains(search));

			}



			return View("Index", QueryableEmps.ToList());
		}








		public IActionResult GetDetailsView(int id)

		{
			//Employee employee = _context.Employees.FirstOrDefault(e=>e.Id==id);
			Employee employee = _context.Employees.Include(emp => emp.Department).FirstOrDefault(emp => emp.Id == id);
			if (employee == null)
			{
				return NotFound();
			}
			else
			{
				return View("Details", employee);
			}

		}
		public string GreatVisitor()
		{
			return "Welcome to Skyline";
		}
		public string CalculateAge(string name, int birthYear)
		{
			return $"Hi,{name}. You are {DateTime.Now.Year - birthYear} years old";
		}

		[HttpGet]
		public IActionResult GetCreateView()
		{
			ViewBag.AllDepartments = _context.Departments.ToList();

			return View("Create");
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		//public IActionResult AddNew(Employee employee)
		//{
		//	if (((employee.HiringDateTime - employee.BirthDate).Days / 365) < 18)
		//	{
		//		ModelState.AddModelError(string.Empty, "Not allowed hiring age (under 18 years)");

		//	}
		//	if (ModelState.IsValid == true)
		//	{


		//		_context.Employees.Add(employee);
		//		_context.SaveChanges();
		//		return RedirectToAction("GetIndexView");
		//	}
		//	else
		//	{
		//		ViewBag.AllDepartments = _context.Departments.ToList();
		//		return View("Create");
		//	}
		//}
		public IActionResult AddNew(Employee employee)
		{
			if (((employee.HiringDateTime - employee.BirthDate).Days / 365) < 18)
			{
				ModelState.AddModelError(string.Empty, "Not allowed hiring age (under 18 years)");
			}

			if (ModelState.IsValid == true)
			{
				if (employee.ImageFile == null)
				{
					employee.ImagePath = "\\images\\No_Image.png";
				}
				else
				{
					// Guid-> Globally Uniqe Identifier  not repeat over the worled
					Guid imageGuid = Guid.NewGuid();
					string imageExtension = Path.GetExtension(employee.ImageFile.FileName);
					employee.ImagePath = "\\images\\" + imageGuid + imageExtension;

					string imageUploadPath = _webHostEnvironment.WebRootPath + employee.ImagePath;

					FileStream imageStream = new FileStream(imageUploadPath, FileMode.Create);
					employee.ImageFile.CopyTo(imageStream);
					imageStream.Dispose();
				}

				_context.Employees.Add(employee);
				_context.SaveChanges();
				return RedirectToAction("GetIndexView");
			}
			else
			{
				ViewBag.AllDepartments = _context.Departments.ToList();
				return View("Create");
			}
		}





		[HttpGet]
		public IActionResult GetEditView(int id)
		{
			//Employee employee = _context.Employees.FirstOrDefault(e => e.Id == id);
			Employee employee = _context.Employees.Find(id);
			if (employee == null)
			{
				return NotFound();
			}
			else
			{
				ViewBag.AllDepartments = _context.Departments.ToList();
				return View("Edit", employee);
			}
		}
		[ValidateAntiForgeryToken]
		[HttpPost]
		public IActionResult EditCurrent(Employee employee)
		{
			if (((employee.HiringDateTime - employee.BirthDate).Days / 365) < 18)
			{
				ModelState.AddModelError(string.Empty, "Not allowed hiring age (under 18 years)");

			}
			if (ModelState.IsValid == true)
			{
				if (employee.ImageFile != null)
				{
					if (employee.ImagePath != "\\images\\No_Image.png")
					{
						System.IO.File.Delete(_webHostEnvironment.WebRootPath + employee.ImagePath);
					}

					// Guid-> Globally Uniqe Identifier  not repeat over the worled
					Guid imageGuid = Guid.NewGuid();
					string imageExtension = Path.GetExtension(employee.ImageFile.FileName);
					employee.ImagePath = "\\images\\" + imageGuid + imageExtension;

					string imageUploadPath = _webHostEnvironment.WebRootPath + employee.ImagePath;

					FileStream imageStream = new FileStream(imageUploadPath, FileMode.Create);
					employee.ImageFile.CopyTo(imageStream);
					imageStream.Dispose();

				}

				_context.Employees.Update(employee);
				_context.SaveChanges();
				return RedirectToAction("GetIndexView");
			}
			else
			{
				ViewBag.AllDepartments = _context.Departments.ToList();
				return View("Edit");
			}


		}


		[HttpGet]
		public IActionResult GetDeleteView(int id)
		{
			//Employee employee = _context.Employees.FirstOrDefault(e => e.Id == id);
			Employee employee = _context.Employees.Find(id);
			if (employee == null)
			{
				return NotFound();
			}
			else
			{
				return View("Delete", employee);
			}
		}
		[ValidateAntiForgeryToken]
		[HttpPost]
		public IActionResult DeleteCurrent(int id)
		{
			//Employee employee = _context.Employees.FirstOrDefault(e => e.Id == id);
			Employee employee = _context.Employees.Find(id);
			if (employee == null)
			{
				return NotFound();
			}
			else
			{
				if (employee.ImagePath != "\\images\\No_Image.png")
				{
					System.IO.File.Delete(_webHostEnvironment.WebRootPath + employee.ImagePath);
				}
				_context.Remove(employee);
				_context.SaveChanges();
				return RedirectToAction("GetIndexView");
			}
		}

	}
}

Skyline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Skyline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Skyline.styles.css" asp-append-version="true" />

    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
	<link href="~/css/darkly.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Skyline</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="GetIndexView">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Departments" asp-action="Index">Departments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Skyline - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>